spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${DB_USERNAME:ticket_admin}
    password: ${DB_PASSWORD:POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: disabled
      password: disabled

jwt:
  secret: ${JWT_SECRET:dGhpc0lzQVZlcnlMb25nQW5kUmFuZG9tU2VjcmV0S2V5Rm9yRGV2ZWxvcG1lbnRPbmx5MTIzNDU2Nzg5MA==}
  access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000}
  refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}

server:
  port: ${SERVER_PORT:8082}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

admin:
  username: ${ADMIN_USERNAME:admin}
  email: ${ADMIN_EMAIL:admin@ticketflow.local}
  password: ${ADMIN_PASSWORD:POSTGRES_PASSWORD}

brevo:
  api-key: ${BREVO_API_KEY:}
  sender-email: ${BREVO_SENDER_EMAIL:}
  sender-name: ${BREVO_SENDER_NAME:Ticket Management Platform}
  
internal:
  service-secret: ${INTERNAL_SERVICE_SECRET:my-super-secret-internal-key-for-service-to-service-communication-only}